name: Data Pipeline Weather

on:
  schedule:
    # Tourne à 10:15, 16:15, 22:15, et 04:15 UTC (Parfait pour chasser les runs 0Z, 6Z, 12Z, 18Z)
    - cron: '15 4,10,16,22 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests pandas pyarrow beautifulsoup4 openpyxl

      - name: Execute Pipeline
        run: python run_dual.py

      - name: Commit and Push Database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Pipeline"
          shopt -s nullglob
          git add data/*.parquet data/*.csv Forecasts/*.xlsx
          git diff-index --quiet HEAD || git commit -m "Pipeline: Base de données synchronisée"
          git push